config/routes.rb
Rails.application.routes.draw do
  devise_for :user, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :restaurants do
    resources :reviews
  end

  root to: 'restaurants#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  validates :name, length: {minimum: 3}, uniqueness: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
  validates :rating, inclusion: (1..5)
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      # user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
      super.tap do |user|
        if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
          user.email = data["email"] if user.email.blank?
        end
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def welcome
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def create
     @restaurant = Restaurant.new(restaurant_params)
     if @restaurant.save
       redirect_to '/restaurants'
     else
       render 'new'
     end
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)

    redirect_to '/restaurants'
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = 'Restaurant deleted successfully'
    redirect_to '/restaurants'
  end

  def restaurant_params
    params.require(:restaurant).permit(:name)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.create(review_params)
    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/index/welcome.html.erb
<h1>Welcome to Yelp Clone</h1>
<%= link_to 'Restaurants', controller: 'restaurants' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>
   <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <% else %>
   <%= link_to "Sign in", new_user_session_path %>
   <%= link_to "Sign up", new_user_registration_path %>
  <% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/restaurants/edit.html.erb
<h1>Edit restaurant</h1>

<%= form_for :restaurant, url: restaurant_path(@restaurant), method: :patch do |x| %>
<%= x.label :name %>
<%= x.text_field :name %>
<%= x.label :description %>
<%= x.text_field :description %>
<br/>
<%= x.label :rating %>
  <% 5.times do |q| %>
    <%= x.label :rating, q+1 %>
    <%= x.radio_button(:rating, q+1) %>
  <% end %>
  <br/>
  <%= x.submit "Update" %>
<% end %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>All of our Restaurants</h1>

<%= link_to 'Add a restaurant', new_restaurant_path %>

<% if @restaurants.empty?  %>
  <h3>No restaurants yet!</h3>
<% else %>
  <table>
    <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Rating</th>
    <th></th>
    </tr>

    <% @restaurants.each do |restaurant| %>
    <tr>
      <td><%= restaurant.name %></td>
      <td><%= restaurant.description %></td>
      <td><%= restaurant.rating %></td>
      <td>
        <%= link_to "Show #{restaurant.name}", restaurant_path(restaurant) %>
        <%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant) %>
        <%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant),
                              method: :delete,
                              data: { confirm: 'Are you sure about deleting?'} %>
        <%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant) %>
      </td>
    </tr>
    <% end %>
  </table>
<% end %>

app/views/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
  <section id='errors' >
   <h2> <%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved.</h2>
   <ul>
     <% @restaurant.errors.full_messages.each do |message| %>
     <li><%= message %></li>
     <% end %>
   </ul>
 </section>
 <% end %>

<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.description %></p>
Rating: <%= @restaurant.rating %>
<% @restaurant.reviews.each do |review| %>
  <ul>
    <li><%= review.thoughts %></li>
    <li><%= review.rating %></li>
  </ul>
<% end %>

<%= link_to 'Back', restaurants_path %>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
<%= f.label :thoughts %>
<%= f.text_field :thoughts %>
<%= f.label :rating %>
<%= f.select :rating, (1..5) %>
<%= f.submit :Submit %>
<% end %>